In [1]:
# import library
import pandas as pd
import re

In [3]:
file = '.\c.xlsx'
df = pd.read_excel(file)

In [4]:
df.columns = ['index', 'province', 'salary', 'cop_name', 'cop_info', 'experience', 'tag', 'benefits']
df.head()

,index,province,salary,cop_name,cop_info,experience,tag,benefits
0,0,Quận Xuhui Thượng Hải Xujiahui,15-25 nghìn,Công nghệ vi mô,Internet Một vòng 20-99 người,3-5 năm đại học,C / C ++,"Thưởng cuối năm, năm bảo hiểm xã hội và một q..."
1,1,Khu mới Phố Đông Thượng Hải Lujiazui,16-25 nghìn,Giới thiệu về Công nghệ mạng của He,Phần mềm máy tính không yêu cầu tài chính cho...,3-5 năm đại học,lập trình mạng,NaN
2,2,Đại liên,10-15 nghìn,Sibaiyi,Phần mềm máy tính không yêu cầu tài chính cho...,1-3 năm giáo dục không giới hạn,MongoDB,"Trợ cấp làm thêm giờ, nghỉ phép hàng năm có l..."
3,3,"Bắc Kinh, Quận Haidian, Tây Bắc Wang",Lương 20-35K 15,Kỷ nguyên dương,Dịch vụ dữ liệu không yêu cầu tài chính cho 1...,3-5 năm đại học,Đi,"Trợ cấp nhà ở, bảo hiểm y tế bổ sung, năm bảo ..."
4,4,Thượng Hải · Quận Yangpu · Yanji,Lương 50-60K 18,Thời trang Lê,Thương mại điện tử không được hỗ trợ 0-20 người,3-5 năm đại học,cấu trúc dữ liệu,"Trợ cấp làm thêm giờ, trà chiều ăn nhẹ, đi du..."

In [5]:
df = df.applymap(lambda s: s.lower() if type(s) == str else s)
df.head(5)

,index,province,salary,cop_name,cop_info,experience,tag,benefits
0,0,quận xuhui thượng hải xujiahui,15-25 nghìn,công nghệ vi mô,internet một vòng 20-99 người,3-5 năm đại học,c / c ++,"thưởng cuối năm, năm bảo hiểm xã hội và một q..."
1,1,khu mới phố đông thượng hải lujiazui,16-25 nghìn,giới thiệu về công nghệ mạng của he,phần mềm máy tính không yêu cầu tài chính cho...,3-5 năm đại học,lập trình mạng,NaN
2,2,đại liên,10-15 nghìn,sibaiyi,phần mềm máy tính không yêu cầu tài chính cho...,1-3 năm giáo dục không giới hạn,mongodb,"trợ cấp làm thêm giờ, nghỉ phép hàng năm có l..."
3,3,"bắc kinh, quận haidian, tây bắc wang",lương 20-35k 15,kỷ nguyên dương,dịch vụ dữ liệu không yêu cầu tài chính cho 1...,3-5 năm đại học,đi,"trợ cấp nhà ở, bảo hiểm y tế bổ sung, năm bảo ..."
4,4,thượng hải · quận yangpu · yanji,lương 50-60k 18,thời trang lê,thương mại điện tử không được hỗ trợ 0-20 người,3-5 năm đại học,cấu trúc dữ liệu,"trợ cấp làm thêm giờ, trà chiều ăn nhẹ, đi du..."

In [63]:
province_lov = 'changsha, chu hải, changchun, zaozhuang, hangzhou, thạch gia trang,
chengdu, dongguan, phật sơn, phúc châu, hạ môn, trường sa, bảo bình, hàng châu,
hợp phì, thâm quyến, tô châu, thượng hải, bắc kinh, hồng kông, thiên tân, vũ hán,
thẩm dương, quảng châu, cáp nhĩ tân, tây an, trùng khánh, thành đô, trường xuân,
thái nguyên, nam kinh, tế nam, đại liên, thanh đảo, lan châu, phủ thuận, trịnh châu'.split(',')

province_lov = [p.strip().lower() for p in province_lov]
province_regex = '|'.join(province_lov)

df['province_recode'] = df.province.str.findall(province_regex).str[0]

In [71]:
def recode_province(df):
    province_lov = 'changsha, chu hải, changchun, zaozhuang, hangzhou, thạch gia trang, chengdu, dongguan, phật sơn, phúc châu, hạ môn, trường sa, bảo bình, hàng châu, hợp phì, thâm quyến, tô châu, thượng hải, bắc kinh, hồng kông, thiên tân, vũ hán, thẩm dương, quảng châu, cáp nhĩ tân, tây an, trùng khánh, thành đô, trường xuân, thái nguyên, nam kinh, tế nam, đại liên, thanh đảo, lan châu, phủ thuận, trịnh châu'.split(',')
    province_lov = [p.strip().lower() for p in province_lov]
    province_regex = '|'.join(province_lov)
    df['province_recode'] = df.province.str.findall(province_regex).str[0]
    return df

df = recode_province(df)

In [76]:
df.salary.str.replace('\d+', '').unique()

D:\Users\bangvh\AppData\Local\Temp/ipykernel_9464/1648918295.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df.salary.str.replace('\d+', '').unique()

array([' - nghìn', ' lương -k ', ' -k ·  lương', 'lương -k ',
       ' - nhân dân tệ / ngày', ' -k', '- nghìn'], dtype=object)

In [78]:
df[df.salary.str.contains("nhân dân tệ / ngày")]

,index,province,salary,cop_name,cop_info,experience,tag,benefits,province_recode
89,89,thanh đảo · quận shibei · cbd,150-200 nhân dân tệ / ngày,công nghệ xinzhong,phần mềm máy tính không được hỗ trợ 20-99 người,6 ngày / tuần 6 tháng cao đẳng,lua,NaN,thanh đảo
108,108,trường xuân · quận triều dương · khu phát tri...,80-100 nhân dân tệ / ngày,changchun boli electronics,phần mềm máy tính không được hỗ trợ 100-499 n...,4 ngày / tuần 9 tháng đại học,nguyên tắc cơ bản về thuật toán,"trợ cấp ăn uống, trợ cấp kỳ nghỉ, năm bảo hiể...",trường xuân
113,113,changsha · changsha county · xingsha tongchen...,150-200 nhân dân tệ / ngày,thông tin giữ lời hứa của changsha baili ...,các cơ sở đào tạo chưa cung cấp tài chính cho...,6 ngày / tuần 6 tháng cao đẳng,giao dục va đao tạo,"thưởng cuối năm, năm bảo hiểm, trợ cấp kỳ nghỉ",changsha
184,184,thượng hải · quận yangpu · wujiaochang,300-400 nhân dân tệ / ngày,bilibili,hơn 10.000 người đã được liệt kê trên internet,3 ngày / tuần 1 tháng đại học,xử lý hình ảnh đồ họa,"khám sức khỏe định kỳ, thưởng cuối năm, bao ă...",thượng hải

In [81]:
df.salary.str.replace('[^-^\d]', '').unique()

D:\Users\bangvh\AppData\Local\Temp/ipykernel_9464/3261273880.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df.salary.str.replace('[^-^\d]', '').unique()

array(['15-25', '16-25', '10-15', '20-3515', '50-6018', '15-30',
       '15-2013', '15-3014', '18-25', '14-20', '65-7014', '20-4016',
       '12-2413', '15-20', '20-40', '20-30', '14-2013', '5-10', '30-6016',
       '15-2513', '14-2413', '12-24', '25-5016', '20-4014', '30-6015',
       '25-35', '9-14', '12-2014', '12-20', '50-7015', '18-2514',
       '9-1413', '25-45', '16-2515', '12-1813', '40-70', '30-4514',
       '20-25', '8-1515', '15-2015', '15-16', '11-2213', '20-35', '6-11',
       '10-1513', '15-27', '7-1213', '25-5014', '15-19', '12-17', '15-28',
       '18-35', '30-4515', '11-2013', '13-26', '15-3013', '30-60',
       '150-200', '8-13', '20-2513', '12-2415', '30-6014', '15-18',
       '80-100', '25-3515', '4-8', '30-5015', '10-1514', '11-20', '6-10',
       '30-35', '23-4515', '8-12', '8-1313', '12-2214', '2-3', '14-2514',
       '18-2513', '20-3013', '7-14', '6-8', '25-5015', '25-40', '11-22',
       '15-2514', '13-2314', '16-3014', '11-2015', '12-18', '25-4014',
       '7-12', '12-14', '15-3015', '23-40', '20-4015', '300-400', '5-8',
       '13-2513', '8-1213', '18-3513', '9-1213', '7-10', '14-28', '11-15',
       '15-3016', '15-2213', '12-23', '5-1013', '14-23', '18-3014',
       '13-2014', '20-4013', '13-1814', '10-1515', '10-11', '18-3515',
       '20-28', '13-17', '10-14', '14-25', '8-10', '35-55', '30-4516',
       '6-9'], dtype=object)

In [97]:
df[df.salary.str.replace('[^-^\d]', '')=='15-2013']

D:\Users\bangvh\AppData\Local\Temp/ipykernel_9464/3459842579.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df[df.salary.str.replace('[^-^\d]', '')=='15-2013']

,index,province,salary,cop_name,cop_info,experience,tag,benefits,province_recode
6,6,thượng hải,lương 15-20k 13,công nghệ máy tính thượng hải zhuoyou,truyền thông / thiết bị mạng 20-99 người,1-3 năm đại học,sql,"trợ cấp thông tin liên lạc, trợ cấp đi lại, n...",thượng hải

In [143]:
df.salary.str.findall("\d+\-\d+").str[0].isnull().sum()

0

In [157]:
df

,index,province,salary,cop_name,cop_info,experience,tag,benefits,province_recode,salary_up,salary_low,salary_mean
0,0,quận xuhui thượng hải xujiahui,15-25 nghìn,công nghệ vi mô,internet một vòng 20-99 người,3-5 năm đại học,c / c ++,"thưởng cuối năm, năm bảo hiểm xã hội và một q...",thượng hải,25000,15000,20000
1,1,khu mới phố đông thượng hải lujiazui,16-25 nghìn,giới thiệu về công nghệ mạng của he,phần mềm máy tính không yêu cầu tài chính cho...,3-5 năm đại học,lập trình mạng,NaN,thượng hải,25000,16000,20500
2,2,đại liên,10-15 nghìn,sibaiyi,phần mềm máy tính không yêu cầu tài chính cho...,1-3 năm giáo dục không giới hạn,mongodb,"trợ cấp làm thêm giờ, nghỉ phép hàng năm có l...",đại liên,15000,10000,12500
3,3,"bắc kinh, quận haidian, tây bắc wang",lương 20-35k 15,kỷ nguyên dương,dịch vụ dữ liệu không yêu cầu tài chính cho 1...,3-5 năm đại học,đi,"trợ cấp nhà ở, bảo hiểm y tế bổ sung, năm bảo ...",bắc kinh,35000,20000,27500
4,4,thượng hải · quận yangpu · yanji,lương 50-60k 18,thời trang lê,thương mại điện tử không được hỗ trợ 0-20 người,3-5 năm đại học,cấu trúc dữ liệu,"trợ cấp làm thêm giờ, trà chiều ăn nhẹ, đi du...",thượng hải,60000,50000,55000
...,...,...,...,...,...,...,...,...,...,...,...,...
295,295,changde,12-24 nghìn,chinasoft international,phần mềm máy tính đã được liệt kê cho hơn 10....,đại học trong vòng 1 năm,c ++,"xe đưa đón miễn phí, trợ cấp kỳ nghỉ, thưởng ...",NaN,24000,12000,18000
296,296,vũ hán · quận giang hạ · thung lũng quang học,7-12 nghìn,vũ hán oppo,phần mềm máy tính không yêu cầu tài chính cho...,kinh nghiệm đại học không giới hạn,linux,"nghỉ phép hàng năm có lương, trợ cấp tiền ăn, ...",vũ hán,12000,7000,9500
297,297,vũ hán · quận giang hạ · đông thung lũng quan...,lương 18-30k 14,shanghai united imaging,thiết bị / dụng cụ y tế b vòng 1000-9999 người,bằng thạc sĩ không giới hạn,c / c ++,"trợ cấp ăn uống, trợ cấp kỳ nghỉ, xe đưa đón ...",vũ hán,30000,18000,24000
298,298,thiên tân · quận dongli · sân bay,13-20k · 14 lương,công nghệ tianyi,tàu / hàng không / không gian vũ trụ 20-99 người,1-3 năm đại học,linux,"trà chiều với đồ ăn nhẹ, trợ cấp kỳ nghỉ, thư...",thiên tân,20000,13000,16500
299,299,cáp nhĩ tân · quận pingfang,10-14 nghìn,công nghệ cao harbin tianjian,phần cứng thông minh không được hỗ trợ 20-99 ...,3-5 năm đại học cơ sở,c / c ++,"trợ cấp ăn uống, đi lại cho nhân viên, khám s...",cáp nhĩ tân,14000,10000,12000

In [156]:
def recode_salary(s):
    w = 1
    if 'k' in s or 'nghìn' in s:
        w *= 1_000
    if 'nhân dân tệ / ngày' in s:
        w *= 30

    l2u = re.findall("\d+\-\d+", s)[0].split('-')
    l = int(l2u[0]) * w
    u = int(l2u[1]) * w
    return (l, u)

df['salary_low'] = df['salary'].apply(lambda x: recode_salary(x)[0])
df['salary_up'] = df['salary'].apply(lambda x: recode_salary(x)[1])
df['salary_mean'] = df['salary_low'].add(df['salary_up']).divide(2).astype('int')

In [178]:
df.experience.str.findall('\d{1}')

def recode_experience(x):
    try:
        result = re.findall('\d{1}', x)
        result = min([int(i) for i in result])
        return result
    except:
        return 0

df['experience_recode'] = df['experience'].apply(lambda x: recode_experience(x))

In [6]:
import pandas as pd
df = pd.read_pickle('data.pkl')
df.shape[0]

300

In [60]:
df['tag'].value_counts()
top5 = df['tag'].value_counts().head(5).index.to_list()
df.mask(df['tag'].isin(top5), 'else')

[' c ++', ' linux', ' cấu trúc dữ liệu', ' python', ' qt']

In [8]:
df['tag'].value_counts().reset_index()

                     index  tag
0                     c ++   59
1                    linux   28
2         cấu trúc dữ liệu   28
3                   python   22
4                       qt   18
..                     ...  ...
58                phần mềm    1
59         huấn luyện viên    1
60          phát triển web    1
61   phát triển khách hàng    1
62                c ++ / c    1

[63 rows x 2 columns]